# Generated by Django 3.1 on 2021-05-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_oraganisor',
            field=models.BooleanField(default=True),
        ),
    ]
